---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-puppetdb-sd.fullname" $ }}
  {{- if .Values.prometheusPuppetdbSd.outputSecretNamespaceOverride }}
  namespace: {{ .Values.prometheusPuppetdbSd.outputSecretNamespaceOverride }}
  {{- end }}
  labels:
    {{- include "prometheus-puppetdb-sd.labels" $ | nindent 4 }}
stringData:
  autosign_psk: {{ .Values.prometheusPuppetdbSd.init.psk | quote }}
